/*
 * GENERATED by scripts/build-gradient-frames.mjs — do not edit by hand.
 *
 * Every frame listed here exists as a file under public/images/frames/. Run the
 * script again after adding a brand or changing which frames are offered.
 */

export type Gradient = {
  key: string;
  label: string;
  /** The Lottie source, for viewers who choose to run it rather than a still. */
  animation: string;
  /** Selectable frames, in order. */
  frames: number[];
  /** The frame a card shows until a viewer picks otherwise. Null plays the animation. */
  defaultFrame: number | null;
};

export const GRADIENTS: Record<string, Gradient> = {
  pura: {
    key: "pura",
    label: "Pura",
    animation: "/animations/Gradient BG 3.json",
    frames: [0, 60, 120, 180, 240, 300, 360, 420, 480, 540],
    defaultFrame: null,
  },
  adib: {
    key: "adib",
    label: "ADIB",
    animation: "/animations/gradient-adib.json",
    frames: [0, 60, 120, 180, 240, 300, 360, 420, 480, 540],
    defaultFrame: null,
  },
  clientele: {
    key: "clientele",
    label: "Clientele",
    animation: "/animations/gradient-clientele.json",
    frames: [0, 60, 120, 180, 240, 300, 360, 420, 480, 540],
    defaultFrame: null,
  },
  nedbank: {
    key: "nedbank",
    label: "Nedbank",
    animation: "/animations/gradient-nedbank.json",
    frames: [0, 60, 120, 180, 240, 300, 360, 420, 480, 540],
    defaultFrame: null,
  },
  absa: {
    key: "absa",
    label: "ABSA",
    animation: "/animations/gradient-absa.json",
    frames: [0, 60, 120, 180, 240, 300, 360, 420, 480, 540],
    defaultFrame: null,
  },
};

/** The still for one frame of one brand. */
export function frameSrc(key: string, frame: number): string {
  return `/images/frames/${key}-${frame}.svg`;
}
